#!/bin/bash


killall conky
sleep 2s

conky -c $HOME/.config/conky/date.conf &> /dev/null &
conky -c $HOME/.config/conky/updates.conf &> /dev/null &
conky -c $HOME/.config/conky/bar1.conf &> /dev/null &
conky -c $HOME/.config/conky/bar2.conf &> /dev/null &
conky -c $HOME/.config/conky/bar3.conf &> /dev/null &
conky -c $HOME/.config/conky/bar4.conf &> /dev/null &
conky -c $HOME/.config/conky/bar5.conf &> /dev/null &
conky -c $HOME/.config/conky/bar6.conf &> /dev/null &


#conky -c $HOME/.config/conky/test.conf &> /dev/null &
